#ifndef TV5725_VIDEO_SOURCE_LINE_H_
#define TV5725_VIDEO_SOURCE_LINE_H_

// The counter a capture window is placed in: how long it is, how much of it the
// sync interval takes, and which end of it that interval sits on. Turning those
// into a window is CaptureWindow's. docs/firmware-geometry-engine.md

#include <stdint.h>

#include "HsyncPulse.h"

namespace Tv5725 {

class VideoSourceLine {
public:
    // Blanking the capture path writes past the hsync pulse where the line
    // doubler is in circuit, which a window opened at the pulse's end captures
    // as the saturated green Y=U=V=0 decodes to. It bounds where a window may
    // OPEN and displaces nothing: the video behind it is where IF_HBIN_SP's own
    // line reset put it.
    //
    // **It is not a time and not a fraction of the line.** 17 was measured at
    // PLLAD_MD 2506, where the same time would be 15 units here and the same
    // fraction 15 as well -- both under what the bench needs. Two dividers, and
    // what they agree on is a count of UNITS.
    // docs/investigations/tail-green.md
    static const uint16_t DoubledHeadBlankingUnits = 22;

    // The whole line is available. The exclusion is the HSYNC pulse and there
    // is no vertical equivalent.
    explicit VideoSourceLine(uint16_t units);

    VideoSourceLine(uint16_t units, uint16_t syncUnits);

    // The frame, for a counter that zeroes on the vertical sync pulse's
    // TRAILING edge: video starts at the counter's own origin, so there is no
    // interval to exclude and no head blanking.
    static VideoSourceLine frame(uint16_t units);

    // The frame for a counter the video reaches late, which is the sync
    // separator's path: the video sits that many units behind the origin.
    // Nothing is excluded at the head -- no hardware facility measures the
    // vertical sync interval in these units.
    static VideoSourceLine frame(uint16_t units, uint16_t originLeadUnits);

    // The line the source sends, from the pulse measured off it. The pulse is
    // that fraction of `units`, and nothing here is a constant for one source:
    // a 0.121 duty source excludes nearly twice what a 0.071 one does.
    //
    // NOTHING IS SUBSTITUTED FOR AN IMPLAUSIBLE DUTY. An HsyncPulse has already
    // been judged a pulse where it was taken, so there is no reading here to
    // refuse -- and a fallback placed the window from a guess that happened to
    // suit the bench source to one unit, which made every other mode wrong and
    // invisible. HsyncPulse.h
    //
    // THE PULSE IS AT THE HEAD WHATEVER POLARITY THE SOURCE SENDS, because
    // SyncProcessor::normaliseHsyncPolarity() inverts a high-active one before
    // the count is taken: every source reaches this counter as a low-active
    // pulse on the leading edge. Compensating for the polarity here applies it
    // a second time and opens the window a whole sync width early.
    // ../../../../docs/investigations/the-capture-floor-followed-a-normalised-polarity.md
    //
    // `separated` is whether the source's hsync is regenerated by the sync
    // separator rather than arriving on its own line, which is composite sync
    // and sync on green both. The separator's output reaches this counter late,
    // so the counter's origin sits SeparatorOriginPerMille of the line after the
    // edge a video standard counts from.
    static VideoSourceLine forDuty(uint16_t units, const HsyncPulse &pulse,
                                   bool lineDoubled, bool separated);

    // How far the sync separator moves this counter's origin, in thousandths of
    // the line. **A FRACTION, NOT A COUNT** -- measured 6.96% of a 1100-unit
    // line and 7.1..7.5% of a 1446-unit one, where a count fitted to either is
    // 40% wrong on the other.
    // ../../../../docs/investigations/the-separator-moves-the-counters-origin.md
    static const uint16_t SeparatorOriginPerMille = 70;

    // The same delay on the vertical, where it is a COUNT of the source's own
    // lines rather than a fraction of the frame -- measured 15.2 lines of a
    // 525-line frame and 16.6 of a 312-line one, where a fraction fitted to
    // either is 80% wrong on the other.
    // ../../../../docs/investigations/the-separator-moves-the-counters-origin.md
    static const uint16_t SeparatorFrameLeadLines = 16;

    // Where the counter rolls over.
    uint16_t units() const;

    // How much of the counter the sync interval takes.
    uint16_t syncUnits() const;

    // How far the video a standard states sits BEHIND this counter's origin, in
    // units. The sync interval on a counter zeroed by the pulse's trailing edge,
    // the separator's delay on one it reaches late, and zero where the origin is
    // the edge the standard itself counts from.
    uint16_t originLeadUnits() const;

    // What the capture path writes over beyond the sync interval, at the head.
    uint16_t headBlankingUnits() const;

private:
    VideoSourceLine(uint16_t units, uint16_t syncUnits,
                    uint16_t headBlankingUnits, uint16_t originLeadUnits);

    uint16_t units_;
    uint16_t syncUnits_;
    uint16_t headBlankingUnits_;
    uint16_t originLeadUnits_;
};

}  // namespace Tv5725

#endif  // TV5725_VIDEO_SOURCE_LINE_H_
